@startuml
start
:Ввести n;
if (n == 0?) then (так)
  :Повернути 0;
  stop
elseif (n == 1?) then (так)
  :Повернути 1;
  stop
else (ні)
  :fib(n-1);
  :fib(n-2);
  :Повернути fib(n-1) + fib(n-2);
  stop
endif
@enduml
